mixed-port: 7890
allow-lan: true
mode: rule

proxies:
  - name: "Safe Node"
    type: ss
    server: 1.1.1.1
    port: 443
    cipher: aes-128-gcm
    password: test

proxy-groups:
  - name: "🚀 Proxy"
    type: select
    proxies:
      - Safe Node

rules:
  - MATCH,🚀 Proxy
